project:
  title: "Example"
  type: aether

website:
  navbar: 
    logo: _extensions/aether/nwpage_tree_logo.png
    background: primary
    left: 
      - text: Github
        file: gh/index.qmd
      - text: AWS
        file: aws/aws_index.qmd
      - text: Azure
        file: azure/azure_index.qmd

    search: true
    # logo: images/doh_logo.png
    pinned: false
    
    right:
      - icon: github
        href: https://github.com/NW-PaGe/standards
        aria-label: GitHub
      - icon: file-richtext
        href: https://nwpage.org/
        aria-label: NW-PaGe
      - icon: file-earmark-pdf-fill
        href: https://github.com/NW-PaGe/standards/blob/main/nw-page-policies.pdf
        aria-label: NW-PaGe PDF

  sidebar:
    # background: '#f8f9fa'
    # alignment: left
    # style: floating
    # border: true
    # search: true
    - id: gh
      collapse-level: 2
      contents:
        - section: "Github"
          href: gh/index.qmd
          contents: 
          - section: "Policies"
            contents:
              - gh/contribute.qmd
              - gh/security.qmd
              - gh/policies.qmd
              - gh/lic.qmd
              - gh/reproduce.qmd
          - section: "Tutorials"
            contents:
              - gh/release.qmd
              - gh/renv.qmd
              - gh/templates.qmd
              - gh/git.qmd
              - gh/how_to.qmd
              # - gh/*.qmd # this glob should work but it's not...

    - id: aws
    - title: "AWS Policies"
      collapse-level: 2
      background: '#f8f9fa'
      alignment: left
      style: floating
      border: true
      search: true
      align: left
      contents:
        - aws/aws_index.qmd

    - id: azure
    - title: "Azure Policies"
      collapse-level: 2
      background: '#f8f9fa'
      alignment: left
      style: floating
      border: true
      search: true
      align: left
      contents:
        - azure/azure_index.qmd
    
  page-footer:
    left: "🍦"
    background: "#fdfdfd"

format:
  aether-html:
    toc: true



